package sk.cyberl.certsigner.logging;

/**
 * Enumeration of possible provenance sources for certificate attributes and extensions.
 */
public enum AttributeSource {

    /**
     * Sourced from a Certificate Signing Request (CSR).
     */
    CSR("CSR"),

    /**
     * Sourced from command-line arguments (CLI).
     */
    CLI("CLI"),

    /**
     * Default fallback generated by the application.
     */
    DEFAULT("DEFAULT"),

    /**
     * Sourced or derived from Azure Key Vault HSM key metadata.
     */
    KEY_VAULT("KEY_VAULT");

    private final String label;

    AttributeSource(String label) {
        this.label = label;
    }

    /**
     * Returns the formatted label representation (e.g. "[CSR]").
     *
     * @return Formatted tag string.
     */
    public String getTag() {
        return "[" + label + "]";
    }

    /**
     * Returns the raw label string.
     *
     * @return Label string.
     */
    public String getLabel() {
        return label;
    }

    @Override
    public String toString() {
        return getTag();
    }
}
